# Generated by Django 3.1.3 on 2020-11-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdvend', models.IntegerField(default=0)),
                ('dsnome', models.CharField(max_length=50)),
                ('cdtab', models.IntegerField(default=0)),
                ('dtnasc', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdcl', models.IntegerField(default=0)),
                ('dsnome', models.CharField(max_length=50)),
                ('idtipo', models.TextField(max_length=2)),
                ('dslim', models.DecimalField(decimal_places=1, default=0, max_digits=100)),
                ('cdvend', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landsys_register.vendedores')),
            ],
        ),
    ]
