# Generated by Django 3.1.3 on 2020-11-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landsys_register', '0002_auto_20201109_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cdvend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landsys_register.vendedores'),
        ),
    ]
